-- The schema now lives in migrations/, applied with:
--
--   npx wrangler d1 migrations apply javi-em-wedding-pics --local
--   npx wrangler d1 migrations apply javi-em-wedding-pics --remote
--
-- This file is kept only so the old path doesn't dead-end.
